/* EXERCICIO OFICINA */

CREATE DATABASE PROJETO_OFICINA;

CREATE TABLE CARRO(
	IDCARRO INT,
	MARCA VARCHAR(15)	NOT NULL
); 

CREATE TABLE COR(
	IDCOR INT,
	COR VARCHAR (15),
	ID_CARRO INT
);


CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30) NOT NULL,
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	TIPO ENUM('CEL','RES','COM'),
	NUMERO VARCHAR (15),
	ID_CLIENTE INT
);

ALTER TABLE CARRO ADD CONSTRAINT PK_CARRO
PRIMARY KEY (IDCARRO);

ALTER TABLE CARRO
 MODIFY IDCARRO INT AUTO_INCREMENT;

ALTER TABLE COR ADD CONSTRAINT PK_COR
PRIMARY KEY (IDCOR);

ALTER TABLE COR
 MODIFY IDCOR INT AUTO_INCREMENT;

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (IDCLIENTE);

ALTER TABLE CLIENTE
MODIFY IDCLIENTE INT AUTO_INCREMENT;

ALTER TABLE TELEFONE ADD CONSTRAINT PK_TELEFONE
PRIMARY KEY (IDTELEFONE);

ALTER TABLE TELEFONE
MODIFY IDTELEFONE INT AUTO_INCREMENT;

ALTER TABLE COR ADD CONSTRAINT FK_CARRO_COR
FOREIGN KEY (ID_CARRO) REFERENCES CARRO(IDCARRO);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CARRO_CLIENTE
FOREIGN KEY (ID_CARRO) REFERENCES CARRO(IDCARRO);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE
MODIFY ID_CARRO INT NOT NULL;

ALTER TABLE COR
MODIFY COR VARCHAR(15) NOT NULL;

ALTER TABLE COR
MODIFY ID_CARRO INT NOT NULL;

ALTER TABLE TELEFONE
MODIFY TIPO ENUM('CEL','COM','RES') NOT NULL;

ALTER TABLE TELEFONE
MODIFY NUMERO VARCHAR(15) NOT NULL;

ALTER TABLE TELEFONE
MODIFY ID_CLIENTE  INT NOT NULL;







